// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO34H6kpfAS61E0NypWyR9UHYnPRuNxXM',
    appId: '1:485915854974:web:406c6f240061a8eb30f02f',
    messagingSenderId: '485915854974',
    projectId: 'learn-firebase-9a799',
    authDomain: 'learn-firebase-9a799.firebaseapp.com',
    storageBucket: 'learn-firebase-9a799.firebasestorage.app',
    measurementId: 'G-8V4KGJZ1TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_tSRVcZE0pL27RBF2ulXl1JMfygCmPes',
    appId: '1:485915854974:android:6737b691b912b03230f02f',
    messagingSenderId: '485915854974',
    projectId: 'learn-firebase-9a799',
    storageBucket: 'learn-firebase-9a799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzGzYagYbHE_uVWvbwofK6ROLl-oV1dGM',
    appId: '1:485915854974:ios:776b8fb3ded92eac30f02f',
    messagingSenderId: '485915854974',
    projectId: 'learn-firebase-9a799',
    storageBucket: 'learn-firebase-9a799.firebasestorage.app',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzGzYagYbHE_uVWvbwofK6ROLl-oV1dGM',
    appId: '1:485915854974:ios:776b8fb3ded92eac30f02f',
    messagingSenderId: '485915854974',
    projectId: 'learn-firebase-9a799',
    storageBucket: 'learn-firebase-9a799.firebasestorage.app',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO34H6kpfAS61E0NypWyR9UHYnPRuNxXM',
    appId: '1:485915854974:web:ccb0c51a40b2abe430f02f',
    messagingSenderId: '485915854974',
    projectId: 'learn-firebase-9a799',
    authDomain: 'learn-firebase-9a799.firebaseapp.com',
    storageBucket: 'learn-firebase-9a799.firebasestorage.app',
    measurementId: 'G-5Q71NVCPQ8',
  );
}
